import js from "@eslint/js";
import tsParser from "@typescript-eslint/parser";
import tsPlugin from "@typescript-eslint/eslint-plugin";
import vuePlugin from "eslint-plugin-vue";
import vueParser from "vue-eslint-parser";
import prettier from "eslint-config-prettier";
import unusedImports from "eslint-plugin-unused-imports";

export default [
  {
    ignores: [
      "public/**/*",
      "server/**/*",
      "middleware/**/*",
      "layouts/**/*",
      "*.config.{js,ts}",
      ".nuxt/**/*",
      "composables/**/*",
    ],
  },
  js.configs.recommended,
  {
    files: ["**/*.vue", "**/*.ts"],
    languageOptions: {
      parser: vueParser,
      parserOptions: {
        parser: tsParser,
        ecmaVersion: 2021,
        sourceType: "module",
      },
      globals: {
        window: "readonly",
        console: "readonly",
        reloadNuxtApp: "readonly",
        nuxtApp: "readonly",
        defineNuxtPlugin: "readonly",
        useRuntimeConfig: "readonly",
        useRoute: "readonly",
        useRouter: "readonly",
        useState: "readonly",
        useHead: "readonly",
        useAsyncData: "readonly",
        useFetch: "readonly",
        useLazyFetch: "readonly",
        useLazyAsyncData: "readonly",
        useError: "readonly",
        clearError: "readonly",
        abortNavigation: "readonly",
        addRouteMiddleware: "readonly",
        defineNuxtRouteMiddleware: "readonly",
        defineI18nConfig: "readonly",
        defineAppConfig: "readonly",
        useNuxtApp: "readonly",
        useToast: "readonly",
        useCookie: "readonly",
        useColorMode: "readonly",
        useHeaderState: "readonly",
        useURLState: "readonly",
        useChatState: "readonly",
        useAuthState: "readonly",
        useLanguageState: "readonly",
      },
    },
    plugins: {
      vue: vuePlugin,
      "@typescript-eslint": tsPlugin,
      "unused-imports": unusedImports,
    },
    rules: {
      ...vuePlugin.configs.recommended.rules,
      "no-console": "off",
      "no-debugger": process.env.NODE_ENV === "production" ? "warn" : "off",
      "vue/multi-word-component-names": "off",
      "@typescript-eslint/no-explicit-any": "warn",
      "@typescript-eslint/explicit-module-boundary-types": "off",
      "vue/no-v-html": "off",
      "vue/require-default-prop": "off",
      "vue/no-v-model-argument": "off",
      "@typescript-eslint/no-unused-vars": "off",
      "unused-imports/no-unused-imports": "error",
      "unused-imports/no-unused-vars": [
        "error",
        {
          vars: "all",
          varsIgnorePattern: "^_",
          args: "after-used",
          argsIgnorePattern: "^_",
        },
      ],
    },
  },
  {
    files: ["**/*.{js,ts}"],
    languageOptions: {
      parser: tsParser,
      parserOptions: {
        ecmaVersion: 2021,
        sourceType: "module",
      },
      globals: {
        window: "readonly",
        console: "readonly",
        navigateTo: "readonly",
        reloadNuxtApp: "readonly",
        nuxtApp: "readonly",
        defineNuxtPlugin: "readonly",
        useRuntimeConfig: "readonly",
        useRoute: "readonly",
        useRouter: "readonly",
        useState: "readonly",
        useHead: "readonly",
        useAsyncData: "readonly",
        useFetch: "readonly",
        useLazyFetch: "readonly",
        useLazyAsyncData: "readonly",
        useError: "readonly",
        clearError: "readonly",
        abortNavigation: "readonly",
        addRouteMiddleware: "readonly",
        defineNuxtRouteMiddleware: "readonly",
        defineI18nConfig: "readonly",
        defineAppConfig: "readonly",
        useNuxtApp: "readonly",
        useToast: "readonly",
        useCookie: "readonly",
        useColorMode: "readonly",
        useHeaderState: "readonly",
        useURLState: "readonly",
        useChatState: "readonly",
        useAuthState: "readonly",
        useLanguageState: "readonly",
      },
    },
    plugins: {
      "@typescript-eslint": tsPlugin,
      "unused-imports": unusedImports,
    },
    rules: {
      "no-console": "off",
      "no-debugger": process.env.NODE_ENV === "production" ? "warn" : "off",
      "@typescript-eslint/no-explicit-any": "warn",
      "@typescript-eslint/explicit-module-boundary-types": "off",
      "@typescript-eslint/no-unused-vars": "off",
      "unused-imports/no-unused-imports": "error",
      "unused-imports/no-unused-vars": [
        "error",
        {
          vars: "all",
          varsIgnorePattern: "^_",
          args: "after-used",
          argsIgnorePattern: "^_",
        },
      ],
    },
  },
  prettier,
];
